---
- name: NVM, NPM
  hosts: localhost

  vars:
    current_user: "{{ ansible_user_id }}"
    node_version: "24.12.0"
    nvm_dir: "/home/{{ current_user }}/.nvm"

  tasks:
    - name: Download nvm install script
      get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh
        dest: /tmp/nvm-install.sh
        mode: "0755"

    - name: Install nvm for current user
      shell: /tmp/nvm-install.sh
      args:
        creates: "/home/{{ current_user }}/.nvm/nvm.sh"

    - name: Add nvm to .bashrc
      blockinfile:
        path: "/home/{{ current_user }}/.bashrc"
        marker: "# {mark} NVM"
        block: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          export PATH="$NVM_DIR/versions/node/$(nvm current)/bin:$PATH"

    - name: Install Node.js version {{ node_version }}
      ansible.builtin.shell: |
        source {{ nvm_dir }}/nvm.sh
        nvm install {{ node_version }}
      args:
        executable: /bin/bash
        creates: "{{ nvm_dir }}/versions/node/v{{ node_version }}"

    - name: Set alias default to version {{ node_version }}
      ansible.builtin.shell: |
        source {{ nvm_dir }}/nvm.sh
        nvm alias default {{ node_version }}
      args:
        executable: /bin/bash
      changed_when: false

    - name: Check Node version via Bash
      ansible.builtin.shell: |
        source {{ nvm_dir }}/nvm.sh
        node --version
      args:
        executable: /bin/bash
      register: node_check
      changed_when: false

    - name: Print Node version
      ansible.builtin.debug:
        msg: "Installed version is {{ node_check.stdout }}"
