---
- name: NPM global packages
  hosts: localhost

  tasks:
    - name: Install global packages
      community.general.npm:
        name: "{{ item }}"
        path: "/home/{{ ansible_user_id }}"
        global: true
        state: latest
      become: false
      loop:
        - "@google/gemini-cli"
        - "@modelcontextprotocol/server-filesystem"
        - "@fission-ai/openspec"
        - "npm-check-updates"

    - name: Add gemini alias to .bashrc
      blockinfile:
        path: "/home/{{ ansible_user_id }}/.bashrc"
        marker: "# {mark} ANSIBLE MANAGED - gemini-alias"
        block: |
          alias gemini='gemini --yolo'
      become: false
