# ansible-playbook setup.yml --ask-become-pass
---
- name: Debian base setup
  hosts: localhost
  become: true

  vars:
    current_user: "{{ ansible_env.SUDO_USER }}"

  tasks:
    # --- packages ---
    - name: Install base packages
      apt:
        name:
          - tree
          - curl
          - rsync
          - git
          - wget
          - gpg
          - make
          - fzf
          - xclip
          - ca-certificates
          - imagemagick
        state: present
        update_cache: true
